//Tags in medicament left column
export enum TagTypeEnum {
  CLASS,
  SUBSTANCE,
  PRINCEPS,
  GENERIC,
  PRESCRIPTION,
  PREGNANCY_SUBS,
  PREGNANCY_CIS,
  PEDIATRIC_DOCTOR_ADVICE,
  PEDIATRIC_CONTRAINDICATION,
  PEDIATRIC_INDICATION,
  PEDIATRIC_MENTION
}
