//Tags in medicament left column
export enum TagTypeEnum {
  CLASS,
  SUBSTANCE,
  PRINCEPS,
  GENERIC,
  PRESCRIPTION,
  PREGNANCY_PLAN,
  PREGNANCY_MENTION,
  PEDIATRIC_DOCTOR_ADVICE,
  PEDIATRIC_CONTRAINDICATION,
  PEDIATRIC_INDICATION,
  PEDIATRIC_MENTION
}
