services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - dev-network

    env_file:
      - ../.env.local

  # We use PostgreSQL as the database for the application data.
  db-postgres:
    image: postgres:15
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "5432:5432"
    networks:
      - dev-network


  # This is the container for the legacy BDPM MySQL database.
  db-mysql:
    image: mysql:9
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "3306:3306"
    networks:
      - dev-network

  opensearch:
    image: opensearchproject/opensearch:2.19.3
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - discovery.type=single-node # Locally, we only need a single node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m # Set min and max JVM heap sizes to at least 50% of system RAM
      - DISABLE_SECURITY_PLUGIN=true # Disable security plugin for local development (DO NOT use for production)
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - dev-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.3
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    networks:
      - dev-network
    depends_on:
      - opensearch

networks:
  dev-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  opensearch-data:
